export default {
  login: "Dancan1998",
  id: 46091729,
  node_id: "MDQ6VXNlcjQ2MDkxNzI5",
  avatar_url: "https://avatars.githubusercontent.com/u/46091729?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/Dancan1998",
  html_url: "https://github.com/Dancan1998",
  followers_url: "https://api.github.com/users/Dancan1998/followers",
  following_url:
    "https://api.github.com/users/Dancan1998/following{/other_user}",
  gists_url: "https://api.github.com/users/Dancan1998/gists{/gist_id}",
  starred_url: "https://api.github.com/users/Dancan1998/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/Dancan1998/subscriptions",
  organizations_url: "https://api.github.com/users/Dancan1998/orgs",
  repos_url: "https://api.github.com/users/Dancan1998/repos",
  events_url: "https://api.github.com/users/Dancan1998/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/Dancan1998/received_events",
  type: "User",
  site_admin: false,
  name: "Dancan Chibole",
  company: "Still in school",
  blog: "",
  location: "Nairobi, Kenya",
  email: null,
  hireable: true,
  bio: "I am a student pursuing a major in Intelligent Science and Technology",
  twitter_username: null,
  public_repos: 18,
  public_gists: 0,
  followers: 1,
  following: 1,
  created_at: "2018-12-23T18:55:42Z",
  updated_at: "2021-02-08T05:09:29Z",
};

// export default {
//   login: 'john-smilga',
//   id: 42133389,
//   node_id: 'MDQ6VXNlcjQyMTMzMzg5',
//   avatar_url: 'https://avatars3.githubusercontent.com/u/42133389?v=4',
//   gravatar_id: '',
//   url: 'https://api.github.com/users/john-smilga',
//   html_url: 'https://github.com/john-smilga',
//   followers_url: 'https://api.github.com/users/john-smilga/followers',
//   following_url:
//     'https://api.github.com/users/john-smilga/following{/other_user}',
//   gists_url: 'https://api.github.com/users/john-smilga/gists{/gist_id}',
//   starred_url:
//     'https://api.github.com/users/john-smilga/starred{/owner}{/repo}',
//   subscriptions_url: 'https://api.github.com/users/john-smilga/subscriptions',
//   organizations_url: 'https://api.github.com/users/john-smilga/orgs',
//   repos_url: 'https://api.github.com/users/john-smilga/repos',
//   events_url: 'https://api.github.com/users/john-smilga/events{/privacy}',
//   received_events_url:
//     'https://api.github.com/users/john-smilga/received_events',
//   type: 'User',
//   site_admin: false,
//   name: 'John Smilga',
//   company: 'Coding Addict',
//   blog: 'www.johnsmilga.com',
//   location: 'Los Angeles',
//   email: null,
//   hireable: null,
//   bio: 'Creator of Coding Addict',
//   twitter_username: 'john_smilga',
//   public_repos: 152,
//   public_gists: 0,
//   followers: 1495,
//   following: 0,
//   created_at: '2018-08-06T06:48:23Z',
//   updated_at: '2020-07-08T05:01:32Z',
// };
