export default [
  {
    login: "sokeno",
    id: 17051444,
    node_id: "MDQ6VXNlcjE3MDUxNDQ0",
    avatar_url: "https://avatars.githubusercontent.com/u/17051444?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/sokeno",
    html_url: "https://github.com/sokeno",
    followers_url: "https://api.github.com/users/sokeno/followers",
    following_url: "https://api.github.com/users/sokeno/following{/other_user}",
    gists_url: "https://api.github.com/users/sokeno/gists{/gist_id}",
    starred_url: "https://api.github.com/users/sokeno/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/sokeno/subscriptions",
    organizations_url: "https://api.github.com/users/sokeno/orgs",
    repos_url: "https://api.github.com/users/sokeno/repos",
    events_url: "https://api.github.com/users/sokeno/events{/privacy}",
    received_events_url: "https://api.github.com/users/sokeno/received_events",
    type: "User",
    site_admin: false,
  },
];